import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Vacancy } from '../Schemas/vacancy.schema';
import * as sgMail from '@sendgrid/mail';
import { unlink } from 'fs/promises';
import { join } from 'path';

sgMail.setApiKey(process.env.SENDGRID_API_KEY!);

@Injectable()
export class VacancyService {
  constructor(
    @InjectModel('Vacancy') private readonly vacancyModel: Model<Vacancy>,
    @InjectModel('FormField') private readonly formFieldModel: Model<any>, // Adjust the type as needed
  ) {}

  async create(
    data: Record<string, any>,
    files: Record<string, Express.Multer.File[]>,
  ): Promise<Vacancy> {
    const savedFiles: { originalname: string; path: string }[] = [];

    // ✅ Attach uploaded file URLs to the data object and collect metadata
    for (const key in files) {
      const fileArray = files[key];
      if (fileArray.length > 0) {
        // 1. Add URLs to the data (frontend use)
        data[key] = fileArray.map(
          (file) =>
            `${process.env.BASE_URL || 'http://localhost:3000'}/uploads/${file.filename}`,
        );

        // 2. Collect file metadata for deletion later
        for (const file of fileArray) {
          savedFiles.push({
            originalname: file.originalname,
            path: file.filename, // Only the filename, not full URL
          });
        }
      }
    }

    // ✅ Save both data and files
    const created = new this.vacancyModel({
      data,
      files: savedFiles,
    });
    await created.save();

    // Email content construction (unchanged)
    const fullName = data['full_name'] || 'Applicant';
    const userEmail = data['email'] || null;

    const htmlRows = Object.entries(data)
      .map(([key, value]) => {
        let displayValue = value;
        if (Array.isArray(value)) {
          displayValue = value
            .map((v) =>
              typeof v === 'string' && v.startsWith('http')
                ? `<a href="${v}" target="_blank">View File</a>`
                : v.toString(),
            )
            .join(', ');
        } else if (typeof value === 'object') {
          displayValue = JSON.stringify(value);
        } else if (typeof value === 'string' && value.startsWith('http')) {
          displayValue = `<a href="${value}" target="_blank">View File</a>`;
        }

        return `<tr><td style="padding: 8px; font-weight: bold;">${key}</td><td style="padding: 8px;">${displayValue}</td></tr>`;
      })
      .join('');

    const hrHtml = `
    <div style="font-family: Arial, sans-serif; background-color: #f4f6f9; padding: 30px; max-width: 750px; margin: auto; border-radius: 8px; border: 1px solid #d3d3d3;">
      <h2 style="background-color: #004080; color: white; padding: 16px; text-align: center; border-radius: 6px;">
        📥 New Vacancy Application Received
      </h2>
      <p style="font-size: 15px;">Dear HR,</p>
      <p style="font-size: 15px;">You have received a new application through the Leaders College website. Below are the submitted details:</p>
      <table border="1" cellpadding="6" cellspacing="0" style="width: 100%; border-collapse: collapse; background-color: #fff; margin-top: 20px;">
        <thead style="background-color: #e8eef5;"><tr><th>Field</th><th>Value</th></tr></thead>
        <tbody>${htmlRows}</tbody>
      </table>
      <p style="margin-top: 30px; font-size: 13px; color: #888;">This email was automatically generated by the vacancy portal of Leaders International College.</p>
    </div>
  `;

    const userHtml = `
    <div style="font-family: Arial, sans-serif; background-color: #f7fafd; padding: 30px; max-width: 700px; margin: auto; border-radius: 8px; border: 1px solid #cfddee;">
      <h2 style="background-color: #007bff; color: white; padding: 16px; text-align: center; border-radius: 6px;">
        ✅ Application Received
      </h2>
      <p style="font-size: 15px;">Dear <strong>${fullName}</strong>,</p>
      <p style="font-size: 15px;">Thank you for applying for a vacancy at <strong>Leaders International College</strong>. Your application has been received and is currently under review by our HR team.</p>
      <p style="font-size: 15px;">Should your profile match any available openings, we will reach out to you via the contact information you provided.</p>
      <p style="margin-top: 25px;">We appreciate your interest and wish you the best in your career journey.</p>
      <p style="margin-top: 30px;">Sincerely,<br/><strong>HR Department</strong><br/>Leaders International College</p>
    </div>
  `;

    const hrEmail = {
      to: 'omar.hossam3@gmail.com',
      from: {
        email: 'youssefsahhar2406@gmail.com',
        name: 'Vacancy Portal',
      },
      subject: `📩 Vacancy Application - ${fullName}`,
      html: hrHtml,
    };

    const userEmailObj = userEmail
      ? {
          to: userEmail,
          from: {
            email: 'youssefsahhar2406@gmail.com',
            name: 'Leaders International College',
          },
          subject: `✅ Your application has been received, ${fullName}`,
          html: userHtml,
        }
      : null;

    try {
      const emailTasks = [sgMail.send(hrEmail)];
      if (userEmailObj) emailTasks.push(sgMail.send(userEmailObj));

      await Promise.all(emailTasks);
      console.log('✅ Vacancy emails sent');
    } catch (err) {
      console.error(
        '❌ Vacancy Email Error:',
        err.response?.body || err.message,
      );
    }

    return created;
  }

  async findAll() {
    return this.vacancyModel.find().sort({ createdAt: -1 });
  }

  async exportCSV(): Promise<string> {
    const vacancies = await this.vacancyModel.find().lean();
    const formFields = await this.formFieldModel.find().lean();

    const headers = formFields.map((f) => f.label);
    headers.push('Submitted At');

    const rows = [headers.join(',')];

    vacancies.forEach((vac) => {
      const data = vac.data || {};

      const row = formFields.map((field) => {
        const val = data[field.field_name]; // key from schema
        const cell = Array.isArray(val)
          ? `"${val.join(', ').replace(/"/g, '""')}"`
          : `"${(val ?? '').toString().replace(/"/g, '""')}"`;
        return cell;
      });

      const createdAt = vac.createdAt
        ? new Date(vac.createdAt).toLocaleString()
        : 'N/A';
      row.push(`"${createdAt.replace(/"/g, '""')}"`);

      rows.push(row.join(','));
    });

    return rows.join('\n');
  }

  async update(id: string, newData: Record<string, any>) {
    return this.vacancyModel.findByIdAndUpdate(
      id,
      { data: newData },
      { new: true },
    );
  }

  async delete(id: string) {
    console.log(`🧾 Attempting to delete application with ID: ${id}`);

    const application = await this.vacancyModel.findById(id);
    if (!application) {
      console.warn(`❌ No application found with ID: ${id}`);
      throw new Error('Application not found');
    }

    console.log(`📄 Application found. Checking for uploaded files...`);

    if (application.files && Array.isArray(application.files)) {
      console.log(`📁 Found ${application.files.length} file(s) to delete.`);
      for (const file of application.files) {
        const fileName = file?.path?.split('/').pop();
        if (!fileName) {
          console.warn(`⚠️ Skipping file with invalid path:`, file);
          continue;
        }

        const filePath = join(__dirname, '..', '..', 'uploads', fileName);
        console.log(`🔍 Attempting to delete file: ${filePath}`);

        try {
          await unlink(filePath);
          console.log(`✅ Successfully deleted: ${filePath}`);
        } catch (err) {
          console.error(`❌ Error deleting file ${filePath}:`, err);
        }
      }
    } else {
      console.log(`🛑 No files attached to this application.`);
    }

    const result = await this.vacancyModel.findByIdAndDelete(id);
    console.log(`🗑️ Application deleted from DB: ${id}`);
    return result;
  }
}
