import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import {
  StudentApplication,
  StudentApplicationDocument,
} from '../Schemas/studentApplication.schema';
import { Model } from 'mongoose';
import * as sgMail from '@sendgrid/mail';
import { join } from 'path';
import { unlink } from 'fs/promises';
import * as fs from 'fs';

// ✅ Confirm API key
console.log(
  'SENDGRID API KEY (partial):',
  process.env.SENDGRID_API_KEY?.slice(0, 10) || 'Not found',
);

// ✅ Set SendGrid API Key
sgMail.setApiKey(process.env.SENDGRID_API_KEY!);

@Injectable()
export class StudentApplicationService {
  constructor(
    @InjectModel(StudentApplication.name)
    private appModel: Model<StudentApplicationDocument>,
  ) {}

  async submitApplication(
    formData: Record<string, any>,
    files?: Express.Multer.File[],
  ): Promise<any> {
    console.log('📥 Incoming application data:', formData);

    const fileMetadata = Array.isArray(files)
      ? files.map((file) => ({
          originalname: file.originalname,
          path: `uploads/${file.filename}`,
        }))
      : [];
    const attachments: {
      content: string;
      filename: string;
      type: string;
      disposition: string;
    }[] = [];

    if (Array.isArray(files)) {
      for (const file of files) {
        try {
          const fileBuffer = await fs.promises.readFile(file.path); // Read the file from disk
          const base64Content = fileBuffer.toString('base64');

          attachments.push({
            content: base64Content,
            filename: file.originalname,
            type: file.mimetype || 'application/octet-stream',
            disposition: 'attachment',
          });
        } catch (err) {
          console.error(
            `❌ Failed to read file ${file.originalname}:`,
            err.message,
          );
        }
      }
    }

    const createdApp = new this.appModel({
      data: formData,
      files: fileMetadata,
    });

    await createdApp.save();

    const studentName = formData.student_name || 'Student';
    const studentEmail = formData.email;

    const tableRows = Object.entries(formData)
      .map(([key, value]) => {
        const safeValue =
          value === null || value === undefined
            ? ''
            : typeof value === 'object'
              ? JSON.stringify(value)
              : String(value);

        return `<tr>
                <td style="padding: 8px; font-weight: bold;">${key}</td>
                <td style="padding: 8px;">${safeValue}</td>
              </tr>`;
      })
      .join('');

    const fileListHtml = fileMetadata.length
      ? `<ul>${fileMetadata
          .map(
            (file) =>
              `<li><a href="${process.env.Backend_URL}/${file.path}" target="_blank">${file.originalname}</a></li>`,
          )
          .join('')}</ul>`
      : `<p>No files were attached.</p>`;

    // ========================
    // ✅ Email to Admissions
    // ========================
    const admissionsEmail = {
      to: 'omar.hossam3@gmail.com',
      from: {
        email: 'youssefsahhar2406@gmail.com',
        name: 'Student Applications',
      },
      subject: `📥 New Student Application from ${studentName}`,
      html: `
    <div style="font-family: Arial, sans-serif; background-color: #f4f6f9; padding: 30px; max-width: 750px; margin: auto; border-radius: 8px; border: 1px solid #d3d3d3;">
      <h2 style="background-color: #004080; color: white; padding: 16px; text-align: center; border-radius: 6px;">
        📚 New Student Application Submitted
      </h2>
      <p style="font-size: 15px;">Dear Admissions Team,</p>
      <p style="font-size: 15px;">You have received a new student application via the website. Below are the submitted details:</p>
      <table border="1" cellpadding="6" cellspacing="0" style="width: 100%; border-collapse: collapse; background-color: #fff; margin-top: 20px;">
        <thead style="background-color: #e8eef5;">
          <tr><th>Field</th><th>Value</th></tr>
        </thead>
        <tbody>${tableRows}</tbody>
      </table>
      <p style="margin-top: 20px;"><strong>Attached Files:</strong></p>
      ${fileListHtml}
      <p style="margin-top: 30px; font-size: 13px; color: #888;">This message was generated by the Leaders International College student application portal.</p>
    </div>
    `,
      attachments: attachments.length > 0 ? attachments : undefined,
    };

    // ========================
    // ✅ Email to Student
    // ========================
    const userConfirmationEmail = studentEmail
      ? {
          to: studentEmail,
          from: {
            email: 'youssefsahhar2406@gmail.com',
            name: 'Leaders International College',
          },
          subject: `✅ We've received your application, ${studentName}`,
          html: `
      <div style="font-family: Arial, sans-serif; background-color: #f7fafd; padding: 30px; max-width: 700px; margin: auto; border-radius: 8px; border: 1px solid #ccddee;">
        <h2 style="background-color: #007bff; color: white; padding: 16px; text-align: center; border-radius: 6px;">
          Application Received
        </h2>
        <p style="font-size: 15px;">Dear <strong>${studentName}</strong>,</p>
        <p style="font-size: 15px;">Thank you for submitting your application to <strong>Leaders International College</strong>.</p>
        <p style="font-size: 15px;">Our admissions team has received your information and is currently reviewing your application. If your profile aligns with our admission criteria, you will be contacted for further steps.</p>
        <p style="margin-top: 25px;">We wish you the best and appreciate your interest in joining our community.</p>
        <p style="margin-top: 30px;">Sincerely,<br/><strong>Admissions Department</strong><br/>Leaders International College</p>
      </div>
      `,
        }
      : null;

    // ========================
    // ✅ Send Both Emails
    // ========================
    try {
      const tasks = [sgMail.send(admissionsEmail)];
      if (userConfirmationEmail) tasks.push(sgMail.send(userConfirmationEmail));

      await Promise.all(tasks);

      return {
        message:
          '✅ Application saved and emails sent to both student and admissions.',
      };
    } catch (err) {
      console.error(
        '❌ SendGrid Email Error:',
        err.response?.body || err.message,
      );
      throw new Error(
        'Application saved, but failed to send confirmation email.',
      );
    }
  }

  async getAllApplications() {
    const applications = await this.appModel
      .find()
      .sort({ createdAt: -1 })
      .lean()
      .exec();

    return applications.map((app) => {
      const { data = {}, ...rest } = app;

      return {
        ...rest,
        data, // ✅ put data back as its own field
      };
    });
  }

  async deleteApplication(id: string) {
    console.log(`🧾 Attempting to delete student application with ID: ${id}`);

    const application = await this.appModel.findById(id);

    if (!application) {
      console.warn(`⚠️ Student application not found: ${id}`);
      return null;
    }

    console.log('📄 Student application found. Checking for uploaded files...');

    if (Array.isArray(application.files)) {
      console.log(`📁 Found ${application.files.length} file(s) to delete.`);
      for (const file of application.files) {
        try {
          if (file.path) {
            const fileName = file.path.split('/').pop();
            if (fileName) {
              const filePath = join(__dirname, '..', '..', 'uploads', fileName);
              await unlink(filePath);
              console.log(`🗑️ Deleted uploaded file: ${filePath}`);
            } else {
              console.warn(
                `⚠️ Could not extract file name from path: ${file.path}`,
              );
            }
          }
        } catch (err) {
          console.error(`⚠️ Could not delete file ${file.path}:`, err.message);
        }
      }
    }

    const deleted = await this.appModel.findByIdAndDelete(id);
    console.log(`🗑️ Student application deleted from DB: ${id}`);
    return deleted;
  }

  async updateApplication(id: string, updateData: Partial<StudentApplication>) {
    return this.appModel.findByIdAndUpdate(id, updateData, { new: true });
  }

  async getApplicationById(id: string) {
    return this.appModel.findById(id).exec();
  }
}
